unit TestuPersonClass;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uPersonClass, System.Generics.Collections;

type
  // Test methods for class TPerson

  TestTPerson = class(TTestCase)
  strict private
    FPerson: TPerson;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFirstName;
    procedure TestLastName;
    procedure TestSalary;
    procedure TestFullName;
  end;

implementation

procedure TestTPerson.SetUp;
begin
  FPerson := TPerson.Create;
end;

procedure TestTPerson.TearDown;
begin
  FPerson.Free;
  FPerson := nil;
end;

procedure TestTPerson.TestFirstName;
const
  ExpectedValue = 'Fred';
begin
  FPerson.FirstName := 'Fred';

  CheckEqualsString(ExpectedValue, FPerson.FirstName);
end;

procedure TestTPerson.TestFullName;
const
  ExpectedValue = 'Thimsfrabble, Fred';
begin
  FPerson.FirstName := 'Fred';
  FPerson.LastName  := 'Thimsfrabble';

  CheckEqualsString(ExpectedValue, FPerson.FullName);
end;

procedure TestTPerson.TestLastName;
const
  ExpectedValue = 'THIMSFRABBLE';
begin
  FPerson.LastName := 'Thimsfrabble';

  CheckEqualsString(ExpectedValue, FPerson.LastName);
end;

procedure TestTPerson.TestSalary;
const
  ExpectedValue = 50000;
begin
  FPerson.Salary := 50000;

  CheckEquals(ExpectedValue, FPerson.Salary);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPerson.Suite);
end.

